- src/template.rs
> (fix) closure type is inferred now

- src/lib.rs
I tried to make an example more useful than it has to be.
> Fix example in docs to use data from structure to render.

- src/helpers/helper_partial.rs
> (feat) Add ability to set partial context

- src/context.rs
This patch is to add support for:
* `a.b.[0]`
* `a.b.[#comments]`
> key expression support

- Cargo.toml
> bump serde version to 0.7

- src/helpers/helper_raw.rs
- src/template.rs
Fixes #65 #64 
This is an implementation of raw block which allow handlebars syntax within block. Also this corrected a few issues in our previous raw helper.
I kept the `raw` helper as default raw block. You can use any helper for raw helper.
> Raw block/helper

- examples/base0.hbs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sunng87/handlebars-rust/73)
> Fix typo in base0.hbs.

- examples/base1.hbs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sunng87/handlebars-rust/74)
> Fix typo in base1.hbs.

- src/registry.rs
- src/render.rs
- src/template.rs
Added in memory source map to track render error in template. Fixes #78
> Source map and better render error reporting 

- examples/partials.rs
- examples/render.rs
- examples/render_file.rs
- src/context.rs
- src/helpers/helper_each.rs
- src/helpers/helper_lookup.rs
- src/helpers/helper_with.rs
- src/lib.rs
- src/registry.rs
- src/render.rs
- src/template.rs
Fixes sunng87/handlebars-iron#47
You should double check, but I think this should do the trick :)
> Disable rustc-serialize when the serde_type feature is enabled

- examples/render.rs
- src/registry.rs
> Change register file path to AsRef<Path>

- Cargo.toml
- src/context.rs
- src/grammar.rs
- src/helpers/helper_each.rs
- src/helpers/helper_with.rs
- src/lib.rs
- src/render.rs
Attempt to improve the path visitor parser. Dropped Regex based parser for Pest. Improve path root for `with`.
> Path refactoring

- Cargo.toml
- src/lib.rs
- src/registry.rs
Use regex to speed up html entity escape.
> Better escape

- src/grammar.rs
Fixes #138 
Allows syntax like `hello\{{world}}`
> Escaping braces

- src/partial.rs
Fixes #143
There is a bug in tracing template name, that the partial name will be used as template name even after it finished its scope.
> Fix template name check

- Cargo.toml
- README.md
- examples/decorator.rs
- examples/error.rs
- examples/render.rs
- examples/render_file.rs
- src/context.rs
- src/lib.rs
- src/registry.rs
- src/render.rs
> Update serde to 1.0

- src/context.rs
- src/grammar.pest
- tests/root_var.rs
> Initial support for @root var

- Cargo.toml
See release notes: https://github.com/rust-lang/regex/releases/tag/1.0.0
> Update to regex 1.0

- src/helpers/helper_boolean.rs
- src/helpers/mod.rs
- src/lib.rs
- src/macros.rs
- src/registry.rs
Fixes killercup/handlebars-helpers-rust#4
> Add boolean helpers and macro for writing them

- src/helpers/helper_each.rs
- src/helpers/helper_if.rs
- src/helpers/helper_with.rs
- src/value.rs
> includeZero option for if

- src/helpers/helper_log.rs
> level option for log helper

- src/helpers/helper_boolean.rs
(feat) extend helper "eq" and "ne" to any Json type (number, string, array,...)
> extend helper "eq" and "ne" to any Json type

- README.md
I tried to not change the meaning of any of the README, I just wanted to make it read a bit better 😃.
> Improve wording / grammar in the README

- src/registry.rs
- tests/data_helper.rs
> Add support for helper contains non-static borrowed data

- src/error.rs
- src/lib.rs
> Fix warnings on nightly error API

- CHANGELOG.md
- src/registry.rs
- src/render.rs
As handlebars doc shows: https://handlebarsjs.com/guide/expressions.html#helpers
Handlebars will resolve helper with a higher priority than property lookup.
> Fix helper resolution priority

- .travis.yml
- Cargo.toml
- examples/script.rs
- examples/script/goals.rhai
- examples/script/template.hbs
- src/error.rs
- src/helpers/mod.rs
- src/helpers/scripting.rs
- src/lib.rs
- src/registry.rs
> Script helper

- src/grammar.rs
- tests/helper_with_space.rs
This patch is to address potential issue reported in #328.
> Add test for string param with space

- CHANGELOG.md
- Cargo.toml
- src/error.rs
Update rhai to its new version
> Update rhai to 0.15

- src/registry.rs
I have a use case for doing template validation separately from registry setup. With this API I could avoid parsing the templates twice.
> Add ability to register already-parsed templates

- src/grammar.pest
- src/grammar.rs
- src/registry.rs
> Add support for $ expression

- src/registry.rs
> Use bufreader for file loading

- src/helpers/helper_each.rs
- src/helpers/helper_with.rs
> Block context issue for else block in each and with

- src/context.rs
- src/error.rs
Add some message when converting errors into `RenderError`
> Improve error message

- CHANGELOG.md
- src/block.rs
- src/context.rs
- src/helpers/block_util.rs
- src/helpers/helper_each.rs
- src/helpers/helper_with.rs
- src/helpers/mod.rs
- src/render.rs
> Derived value support for with helper 

- src/support.rs
> Add more escape chars

- src/context.rs
- src/render.rs
> Add debugging log for developers to understand what's going on

- CHANGELOG.md
- Cargo.toml
> (feat) rhai up

- src/grammar.pest
- src/grammar.rs
- src/registry.rs
> Parser issue for references starts with null/true/false

- src/block.rs
- src/helpers/helper_each.rs
- src/lib.rs
- src/local_vars.rs
- src/render.rs
Fixes #371 
This patch adds optimization for local variable with fixed names (`@first`, `@last`, `@key` and `@index`).
> Introducing fixed LocalVars

- src/template.rs
> Fixes panic on invalid tag name

- CHANGELOG.md
- Cargo.toml
> (feat) update rhai to 1.0

- src/registry.rs
> Add getter/setter for internal rhai engine

- src/grammar.rs
- src/template.rs
- tests/helper_with_space.rs
> fix: trim at most one line directives #472

- README.md
Seems to have moved in https://github.com/actix/examples/commit/cc3d3562094bce971927088b652ff767ceb92560
> Update link to actix-web example

- src/grammar.pest
- src/grammar.rs
- tests/whitespace.rs
> fix: whitespace elision syntax to be compatible with js version

- src/registry.rs
> feat: add function to reuse context while write into Write #514

- src/partial.rs
> Using both hash and param in partial include

- src/render.rs
Scope: No API breakage/addition only an internal change
> Write instead of format

- README.md
`axum-template` provides `handlebars` integration with Axum
> Include `axum-template` on related projects

- src/helpers/helper_lookup.rs
> Fix looking up provided null value in strict mode

- src/lib.rs
> fix: expose directory source options

- src/helpers/scripting.rs
- src/registry.rs
This patch resolves additional clippy warnings on optional features
> fix: clippy warnings on optional feature tests

- src/helpers/helper_each.rs
> feat: add @index for object iteration

- examples/error.rs
> Fix documentation typo
