src/lib.rs
Fixes #2.
You may also want to consider moving to plain `regex` since `regex_macros` won't work in the stable channel of Rust 1.0. (We may come up with a fix before then using `build.rs` though.)
=> Don't link to regex_macros at runtime.

src/context.rs, src/template.rs
=> rename RingBuf to VecDeque

src/lib.rs, src/template.rs
This makes TemplateError available outside of the crate, and also implements
std::error::Error on it.
=> Make TemplateError accessible

Cargo.toml, src/helpers/helper_lookup.rs, src/lib.rs, src/template.rs
FromPrimitive was removed from the nightly std (not sure about beta), so
we might as well migrate to the num crate which now houses it. This
means we have to manually implement FromPrimitive.
Also no longer need the `core` feature.
=> use num::FromPrimitive instead

Cargo.toml, src/context.rs, src/lib.rs, src/support.rs, src/template.rs
This removes the use of the language features to enable its compilation
on rust stable.
the plugin feature was removed and so was the regex_macros dependency.
Instead of re-building the regular expression each time it needs to be
built, I build it once per `Context` instance, which I think is the next
best thing compared to a global, statically initialized regex.
the collections feature was needed for the str::slice_chars function. I
work around this for now by simply ripping out the slice_chars
implementation from the nightly std and embedding it in the code
directly, which we can use at least until the fate of std slice_chars
is determined.
=> compile on stable

src/helpers/helper_each.rs
Formerly, @last would never be true in #each of a single-element array.
=> Fix @last on a single-element array #each.

Cargo.toml, src/error.rs, src/lib.rs, src/registry.rs, src/template.rs
The patch doesn't make error reporting perfect because there are no line numbers yet. But at least this makes error reporting on par with `rumblebars` that have multiple errors types but not error lines too (the `rumblebars` have somewhat complex dependencies, however).
=> Implement some error reporting (#30)

src/render.rs, src/template.rs
We don't need to explicitly copy strings everywhere, passing slices
often suffices, because parsing copies the original string anyway.
=> Use AsRef wherever possible

src/helpers/helper_partial.rs, src/registry.rs, src/render.rs, src/template.rs
This feature is to add fix for #44 and enhance `RenderContext` for helper developers.
The current implementation uses too much clone which I think can be optimized to use borrowed string for `current_template` name and `root_template` name. But I'm lost in the borrow check... Help is wanted.
=> Tracing current_template and root_template in RenderContext

src/lib.rs, src/registry.rs, src/render.rs
This pull request allows the user to override the way output of `{{expr}}` is escaped. 
While my own use case of disabling escaping completely could be achieved by using `{{{expr}}}` and different escape functions could probably be implemented using custom helpers I think this pull request provides a nicer solution.
I especially think that a rust template engine should be as output format agnostic as possible since the environments in which rust is used are more diverse than those in which JS is used.
Rendering performance seems to be unaffected:
```plain
before:
test parse_template  ... bench:     127,948 ns/iter (+/- 12,205)
test render_template ... bench:      18,471 ns/iter (+/- 7,158)
after:
test parse_template  ... bench:     127,924 ns/iter (+/- 18,775)
test render_template ... …
```
=> (feat) add support for custom escape functions

examples/render_file.rs, src/error.rs, src/lib.rs, src/registry.rs
Fixes #69 
Added a few new APIs to render template without register it, and file a `std::io::Read` source
=> Render string

examples/render.rs, examples/render_file.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_partial.rs, src/helpers/helper_with.rs, src/helpers/mod.rs, src/lib.rs, src/registry.rs, src/render.rs, src/template.rs
Fixes #75 
* Added support for JSON literal in helpers like `{{hello 1 a=true b=3.14 c=ref}}` where `ref` is a reference to your context value, while `1`, `true` and `3.14` are all literal values.
* Return value subexpression are no treated as reference by default, if you want JSON value use literal instead. For example, `foo` will be treated as reference which `"foo"` is string.
* Break change for helper developers, references hash and params are now solved by default, no more `ctx.navigate` is needed.
* Removed `to_string()` implementation from template types.
=> Json literal as param and hash

Cargo.toml, src/error.rs, src/grammar.rs, src/helpers/helper_each.rs, src/lib.rs, src/render.rs, src/template.rs
Fixes #81 
I decided to use [pest](https://github.com/dragostis/pest) to replace current custom parser for maintainability and correctness. 
Tasks:
=> Pest parser

src/context.rs, src/helpers/helper_each.rs, src/helpers/helper_lookup.rs
We're using handlebars-rust in [Habitat](https://www.habitat.sh/). It's fanstastic, thank you!
A [user reported](https://github.com/habitat-sh/habitat/issues/1083) that `../` is not working correctly in an `each` block. Specifically, when a template should be able to use `../` to access a parent value, it instead requires `../../`, as the array index is included in the path as part of the logic in [context:: parse_json_visitor](https://github.com/sunng87/handlebars-rust/blob/565c1353cbc36e81479804510a98123131e0aaf0/src/context.rs#L28). This PR contains a fix for this issue.
Included is a test based off the following manual test via [http://tryhandlebarsjs.com/](http://tryhandlebarsjs.com/):
If I use this template:
```
{{#each a.c}} 
d={{d}} b={{../a.b}} 
{{/each}}
```
and the following …
=> fixed #each helper to access parent via ../ instead of ../../

src/context.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/render.rs
This is to address issue seen at https://github.com/habitat-sh/habitat/issues/1083
The handlebars js implementation has a special path resolver, that when using `../` the base it set to block param root, while using `.` it's local root.
This patch is to keep handlebars-rust behaves same with js impl.
=> Added local path root for #if and #each

src/grammar.rs
Hello -
we've found that template expressions that include the `-` character fail to compile. See the included test which fails without this patch.
The Handlebars grammar specifies identifiers quite differently: https://github.com/wycats/handlebars.js/blob/master/src/handlebars.l#L18-L27
but doesn't exclude `-`.
Cheers -
Dave
=> allow identifiers to contain "-"

src/helpers/helper_with.rs
Fix templates like: 
```
{{#each foo}}
{{#with bar}}
{{../foovar}}
{{/with}}
{{/each}}
```
foovar was not being found.
=> Fix case where with is used inside an each with nested data access

examples/template.hbs, src/context.rs, src/grammar.rs, src/helpers/helper_each.rs, src/helpers/helper_with.rs, src/render.rs, src/template.rs
Fixes #42
Add support for block params like:
```handlebars
{{#each people as |person|}}
...
{{/each}}
```
Steps:
- update built-in helpers
=> Block params [WIP]

.travis.yml, Cargo.toml, src/directives/inline.rs, src/directives/mod.rs, src/error.rs, src/grammar.rs, src/helpers/helper_lookup.rs, src/helpers/helper_partial.rs, src/helpers/mod.rs, src/lib.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs
This patch set is going to implement directive syntax, handlebars 4.0 new partials #85 and decorators #102.
Since the new partial system is incompatible with previous one, it will be implemented as a crate feature which is turned off by default.
=> Handlebars 4.0 Partials 

src/helpers/helper_partial.rs, src/helpers/mod.rs, src/render.rs
Fixes #115 
As reported in #115, the result of subexpression should be treated as string instead of ref. This patch fixes this issue. And also added support for string literal in include (`>`) helper.
=> Correct subexpression behavior

src/support.rs
Fixes #120 
Use a 8KB buffer as initial size to avoid frequent allocation.
=> Default StringWriter buffer size

.travis.yml, Cargo.toml, README.md, examples/partials.rs, examples/partials/base0.hbs, examples/partials/base1.hbs, examples/partials/template2.hbs, examples/partials_legacy/base0.hbs, examples/partials_legacy/base1.hbs, examples/partials_legacy/template2.hbs, src/grammar.rs, src/helpers/helper_partial.rs, src/helpers/mod.rs, src/registry.rs
The `partial4` feature will be made default in next release. Current partial system is moved to feature flag `partial_legacy`.
=> Making partial4 default

examples/partials.rs, src/render.rs
Fixes #128 
When there are multiple levels of template during rendering, keep the original one in error information.
=> Don't overwrite template name in RenderError

README.md
A simple change to the README to link directly to Rocket's `Template` documentation.
=> Link to `Template` in Rocket's contrib.

.travis.yml, Cargo.toml, examples/decorator.rs, examples/error.rs, examples/partials.rs, examples/render-cli.rs, examples/render.rs, examples/render_file.rs, src/context.rs, src/directives/inline.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_lookup.rs, src/helpers/helper_with.rs, src/lib.rs, src/registry.rs, src/render.rs, src/template.rs
Fixes #136 
This patch drops support for rustc_serialize and use serde_json as default type system.
=> Dropping rustc_serialize

src/grammar.rs, src/lib.rs, src/render.rs
Fixes #152 
When object key contains slash `/`, it's ignored by error. This patch should fix it.
=> Fix object key with slash

.travis.yml
Legacy partial system will be dropped in 1.0 release.
=> Dropping feature partial_legacy

src/context.rs, src/directives/inline.rs, src/directives/mod.rs, src/error.rs, src/grammar.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_partial.rs, src/helpers/helper_raw.rs, src/helpers/helper_with.rs, src/helpers/mod.rs, src/lib.rs, src/partial.rs, src/registry.rs, src/render.rs
This patch added error reporting for JSON path. If your JSON path is invalid, handlebars should be able to report it as a `RenderError` and provide some information.
It also aligns partial context with handlebarsjs. For partial like `{{> my_partial a="b"}}`, if current context is a non-object JSON value, it will be ignored. `{"a": "b"}` becomes current context and there's no way to access previous context.
=> Report path error / Fix partial context

Cargo.toml, src/context.rs, src/directives/inline.rs, src/partial.rs, src/registry.rs, src/render.rs
Currently we are using `ctx.extend` to merge partial hash and render data. This approach will:
* ruin context and leave the data out of partial scope
* introduce path issue when partial included in `each`/`with` context
Template to reproduce:
```handlebars
{{#*inline "pp"}}{{a}} {{b}} {{../c}} {{@index}}{{/inline}}
{{#each d}}
{{> pp a="2"}}
{{/each}}
```
Data:
```json
{
"d": [{"b":true}],
"c": "hello"
}
```
Expected result:
```
2 true  0
```
=> Partial scope issue

src/context.rs, src/directives/mod.rs, src/error.rs, src/helpers/helper_each.rs, src/helpers/helper_with.rs, src/partial.rs, src/registry.rs, src/render.rs
Fixes #161
Don't eat `serde_json::error::Error` silently. We will raise `RenderError` when such error returned from serde API. 
Added `cause` for `RenderError` where you can access its root error.
=> Serialize error

src/context.rs, src/directives/mod.rs
From 0.27, `RenderContext` now owns `Context`. During the render process, we need to clone the `RenderContext`, so `Context` and its wrapped data are cloned again and again. This patch made data in `Context` an `Rc`, the clone cost will be pretty cheap.
Address issue #166 .
Benchmark:
```
test large_loop_helper ... bench:   3,242,381 ns/iter (+/- 313,516)
```
Compared with 0.27:
```
test large_loop_helper ... bench: 496,376,347 ns/iter (+/- 148,433,745)
```
0.26:
```
test large_loop_helper ... bench:   3,148,455 ns/iter (+/- 72,797)
```
=> Improve performance for 0.27 change on RenderContext

src/context.rs, src/directives/mod.rs
This is follow up for #167 that I'm now using `Arc` for data ref so we don't have to clone data and create new context when changing data in directives.
The performance is almost identical to the Rc one:
```
test large_loop_helper ... bench:   3,238,791 ns/iter (+/- 187,867)
```
=> Arc for data ref in Context

src/template.rs
I think I covered all the cases here. It did seem a bit repetitive but no more repetitive then the existing code for emitting `RawStrings`. 
Ideally I would have liked to find a way to do this in the grammar itself but I couldn't find a clear path for that. I'm new to the pest syntax but familiar with [scala's parser combinator library](https://github.com/scala/scala-parser-combinators#example) and couldn't find the equivalent of scala's `^^` operator to transform the grammar
=> omit tag escape pattern from resulting RawString element output

src/context.rs, src/grammar.rs, src/helpers/helper_each.rs
Fixes #173 and #174 
This patch is based work done in #175 by @hucal 
Removed path expression:
* a["a"]
* a['a']
Added support for:
* a.[a]
* a.[你好] // unicode
=> Align path impl with original javascript version

src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_raw.rs, src/helpers/helper_with.rs, src/helpers/mod.rs, src/lib.rs, src/render.rs, src/template.rs, tests/subexpression.rs
Fixes #181 
This patch adds support for `HelperDef` to return typed Json value instead of writing it into writer as bytes. This makes it possible to get typed result from subexpression.
=> WIP: Allow HelperDef returns Json value

src/directives/inline.rs, src/helpers/helper_each.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs
Previously, we have template reference in Registry (top level templates, helper inner template, per-registered partials) and RenderContext (partials). It has been a pain to maintain those references with different lifetime, which results in a few clones when associating templates into RenderContext.
This patch use Rc to store templates across the whole library. Based on previous benchmark, the overhead for Rc is not significant so we can keep code clean while not loosing performance.
=> Use Rc to maintain template reference across registry and render context

src/directives/inline.rs, src/helpers/helper_each.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs
Reverts sunng87/handlebars-rust#186
This breaks `Send` and `Sync` for `Registry`, which is required in some web framework
=> Revert "Use Rc to maintain template reference across registry and render context"

src/context.rs, src/partial.rs, src/registry.rs, src/render.rs
Fixes #203 
Added toggle on registry to enable strict_mode on handlebars. Under strict mode, any access to a non-existed key will raise a `RenderError`.
=> Strict mode

examples/decorator.rs, examples/render.rs, examples/render_file.rs, src/directives/inline.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_with.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs, tests/subexpression.rs
IntelliJ can automatically eliminate `try!`. I have run it.
Afterwards, I ran `cargo +stable fmt`, which printed a load of errors about the rustfmt.toml, but seems to have done roughly the right thing; it's removed some trailing commas in places that they probably weren't needed.
=> eliminate use of try!

src/output.rs, src/registry.rs
Partial fix for #190.
There's no reason to have these `&mut`s here. Remove them. No other code changes are necessary, because Rust's stdlib fixes cases where people are already passing in `&mut`.
=> Stop asking for &mut Write in Registry API

src/grammar.pest, src/grammar.rs, src/registry.rs, src/template.rs, tests/escape.rs
Fixes #216 
There are issues with current backslash escape implementation. This patch changed both parser and template processing to ensure backslash was correctly treated.
=> Fix mustach escape

Cargo.toml, examples/render-cli.rs, src/error.rs, src/lib.rs, src/registry.rs
Allow a caller to specify a directory path and an extension, then
register all files in that directory.
Closes #11
=> Implement register_template_directory to Registry 

examples/decorator.rs, examples/render.rs, examples/render_file.rs, src/context.rs, src/directives/inline.rs, src/directives/mod.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_raw.rs, src/helpers/helper_with.rs, src/helpers/mod.rs, src/lib.rs, src/partial.rs, src/registry.rs, src/render.rs, src/support.rs, src/template.rs, src/value.rs, tests/subexpression.rs
Another attempt to fix #206 
In order to use reference from Context, we have to ensure it's immutable across the render process. However, that's conflict with how we use RenderContext. So we have to split `Context` and `RenderContext` for better mutable granularity.
=> Split Context and RenderContext for better mutable granularity 

src/directives/mod.rs, src/helpers/mod.rs, src/lib.rs, src/registry.rs
All credit goes to https://github.com/Jason-Rev/vscode-spell-checker
=> Fix a few typos in the docs

Cargo.toml
This bumps the minimal acceptable versions in Cargo.toml to versions that are compatible with `-Z minimal-versions`. This is part of the process of seeing how hard this is for crates to use in preparation for getting it stabilized for use in CI, specifically upstreaming the changes required to get criterion working with it. It is easy to use if all of your dependencies support it, but much harder if trying to impose it on them.
Also cargo defaults to interpreting version requirements as `^`. So this switched to the shorter form.
=> update some debs for minimal-versions

Cargo.toml, release.toml, src/lib.rs
See the Rust API guideline ([link][1]) for details.
[1]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#crate-sets-html_root_url-attribute-c-html-root
=> (chore) fix the url in #![doc(html_root_url)]

src/partial.rs, src/registry.rs, src/render.rs, src/value.rs
Fixes #247 
Currently in strict mode, any visit to non-existed value will result in a `RenderError`. This is not friendly for helper, which is supposed to be able to process non-existed value as `Null`.
This patch changed this behaviour to check value presence only when it rendered .
=> Better strict mode, only check when output value to template

.travis.yml, Cargo.toml
This ensures our lower bounds in dependencies are accurate
=> CI: add test with minimal versions

Cargo.toml, src/lib.rs, src/render.rs
Replace std collections with Hashbrown/Swiss map. Speeds benchmark up for 10% at most.
=> Hashbrown map

src/grammar.rs, src/helpers/helper_each.rs, src/template.rs
As per https://handlebarsjs.com/builtin_helpers.html#iteration, the order of block parameters is `value` first, `key` second.
=> Swap order of block parameters in each helper

src/lib.rs
Otherwise we can't use `local_rc.push_block_context` in custom tags
=> export BlockParams

src/helpers/helper_each.rs, src/render.rs, tests/block_context.rs
With a single block param, `each` should set it as the value of the container being iterated over.
With two block param, `each` should set the first as the value of the container being iterated over, and the second as the key/index.
=> Support singular and plural block params for each helper

README.md
the crates.io badge is served via https now
=> fixes #284

Cargo.toml, release.toml, src/context.rs, src/lib.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs
Fixes #279
Benchmark shows std hashmap now shares same performance with hashbrown. So we'd better swtich back in next major release.
=> (feat) switch back to std hashmap [#279]

.travis.yml, Cargo.toml, src/error.rs, src/lib.rs, src/registry.rs
As of 2.0, the feature flags of handlebars-rust was a little bit confuse. In this patch, I made:
* `no_dir_source` is now by default, `walkdir` dependency and `register_directory` is only enabled by `dir_source` feature. Webassembly compatibility is now by default.
* `no_logging` feature cleaned up.
=> Reorganize feature flags

src/helpers/helper_each.rs, src/helpers/helper_with.rs
beta 2 introduced a bug that after we reuse render context in `each` and `with` block, some data was not restored on escaping the block. This patch fixes this issue.
=> Path restore

src/context.rs, src/error.rs, src/grammar.pest, src/grammar.rs, src/helpers/helper_each.rs, src/helpers/helper_with.rs, src/json/path.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs
One of key issue with handlebars render performance is because the JSON path expression is parsed on rendering, which provides some flexibility for helper developers. However, in performance critical case like large loop, these path expressions are parsed again and again causing huge waste of CPU time. 
This patch changed this behaviour by breaking JSON path to navigable segments during template parsing. 
#294
=> Parse path during template parse phase

src/block.rs, src/context.rs, src/helpers/helper_each.rs, src/helpers/helper_lookup.rs, src/helpers/helper_with.rs, src/json/path.rs, src/json/value.rs
This patch fixes previous `../` implementation. Now we don't need to track each scope's `local_path_root` and use upper scope's base_path directly. 
This patch provides up to 20% performance improvement against current master.
=> Remove local path root

src/decorators/inline.rs, src/decorators/mod.rs, src/error.rs, src/grammar.pest, src/grammar.rs, src/lib.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs
This patch renames `Directive`s to handlebars' standard name `Decorator`.
=> Rename directive to decorator

src/grammar.pest, src/template.rs, tests/template_names.rs
This change re-enables the ability to use the template names generated by the "walk dirs" feature of handlebars-rust. It generates template names like `foo/bar/baz`, which couldn't be used in 3.0.0, as the character `/` was not allowed in the name of the referenced template.
=> [#312]: Re-enable usage of template names from walk dir

src/registry.rs
I had to check the source code to figure out what was going on, this should help others avoid needing to do that.
=> Document register_templates_directory being dependent on the dir_source feature

src/decorators/mod.rs, src/helpers/mod.rs, src/registry.rs, src/render.rs
* removed `Send + Sync` bound of `HelperDef` for `RenderContext::register_local_helper` and related functions.
* removed `Send + Sync` bound of `DecoratorDef` for `RenderContext::register_local_decorator` and related functions.
* refined some `'static` lifetimes to `'rc`
Background:
I use the `RenderContext` inside a HTTP request (the `Registry` is shared), and I want to register
local-helpers that access the HTTP request (for example a helper that resolves a URL)
=> removed `Send + Sync` bound of `RenderContext.register_local_*`

src/grammar.pest, src/template.rs
This PR fixes a parse error that arises when using paths, containing `/`, as partial block identifiers.
Closes #321
=> Fix incorrect parse error for partial identifiers

README.md, src/block.rs, src/context.rs, src/decorators/mod.rs, src/helpers/mod.rs, src/lib.rs, src/registry.rs, src/render.rs
I was reading through the docs and noticed a few typos, so fixed them as I went along.
=> Fix some typos/grammar in README and doc strings

CHANGELOG.md, src/macros.rs, tests/helper_macro.rs
Fixes #335 
This patch added support for named argument in helper macro `handlebars_helper!`.  The syntax is like:
```rust
handlebars_helper!(is_above, |x: u64, { compare: u64 = 10 }| x > compare);
```
Multiple named arguments are supported with `,` separated. 
When using this helper, you can either 
```handlebars
{{is_above 100 compare=99}} or {{is_above 100}}
```
=> Hash support for helper macro

src/macros.rs, tests/helper_macro.rs
Added support for python's `*args` and `**kwargs` style arguments support for helper macro. 
* `*args` provides a vector of all helper parameters as `&serde_json::Value`
* `**kwargs` provides a map of all helper hash `<&str, &serde_json::Value>`
A usage example is included in test case.
=> Helper macro enhancement

src/helpers/helper_each.rs
This patch fix issue #348 that introduced in #346. 
In #346 we stopped creating block context for empty item in `#each` but still had it popped at the end of each helper, causing block context leak.
=> Fix block context leak

CHANGELOG.md, benches/bench.rs, src/context.rs, src/registry.rs
Fixes #351 
According to our benchmark, the creation of `Context` can take up to 50% time of template rendering, due to data copy in serde_json. 
This patch added two new API to `Registry` aka `Handlebars` to allow user to reuse `Context` and avoid that copy.
I'm considering a better `Context` to avoid copy as much as possible in future release.
=> Allow Context reuse in render API

README.md
tide-handlebars has been added to the tide community crates https://github.com/http-rs/tide/wiki/Community-Crates So adding it to the list on this site too.
=> Add Tide to supported web frameworks

CHANGELOG.md, src/grammar.pest, src/grammar.rs, src/registry.rs
Fixes #357 
It seems I had a terrible mistake in #339 , which should be `&` char instead of `$`. And `$`, as described in https://handlebarsjs.com/guide/expressions.html#literal-segments, is valid as a symbol char.
=> Dollar symbol support

src/grammar.pest, src/grammar.rs, src/partial.rs
You can now pass parameters to partials that are referenced through subexpressions. For example:
```handlebars
{{> (lookup foo "bar") name="value"}}
```
[This syntax is supported by handlebars.js](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22This%20is%20a%20test.%20%7B%7B%3E%20(x%20%40root)%20name%3D%5C%22fred%5C%22%7D%7D%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22two%22%2C%22content%22%3A%22Lets%20test%20%7B%7Bname%7D%7D%22%7D%5D%2C%22input%22%3A%22%7B%7D%22%2C%22output%22%3A%22This%20is%20a%20test.%20Lets%20test%20fred%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper(%5C%22x%5C%22%2C%20()%20%3D%3E%20%5C%22two%5C%22)%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.6%22%7D).
=> Update grammar for partials to allow subexpressions + parameters

src/helpers/helper_each.rs
=> Enable block parameters for derived values in `each` helper

src/helpers/helper_each.rs, src/helpers/helper_lookup.rs, src/helpers/helper_with.rs
This is a further patch to address issue in #355 . `base_value` is inherited in `each` block during iteration. 
We also enabled subexpression value access for `lookup` helper.
=> Fix derived value in each and lookup helper

src/helpers/mod.rs, src/render.rs, tests/helper_macro.rs
Fixes #361 
This patch partially fixed issue as mentioned in #361 that result of helper call should be escaped by default.
Further support for `{{{html expression}}}` that doesn't escape the result will be supported in 4.0
=> Escaping helper expression results

src/helpers/helper_each.rs
Previously things like `{{#each "foo"}}` were render errors. Now non-iterable values are treated like empty iterables. This brings handlebars-rust's behavior closer in line with the original JavaScript [library](https://handlebarsjs.com/).
=> Make #each handle non-iterable values like the original JavaScript version

src/grammar.pest, src/grammar.rs, src/render.rs, src/template.rs, tests/helper_macro.rs
This is a follow up of #373 that adds helper call support in html expression.
This patch introduces break change in `TemplateElement` API.
=> Helper call support in html expression

src/helpers/helper_each.rs, src/helpers/helper_lookup.rs, src/helpers/helper_with.rs
Fixes #384 
This patch add strict mode support for `each`, `with` and `lookup` helper. 
When inverse block was not defined for `each` and `with`, it throws `RenderError` on null value and invalid values.
=> Strict helpers

.travis.yml, src/registry.rs
=> Fix dir source for windows

CHANGELOG.md, Cargo.toml, README.md, examples/dev_mode.rs, examples/dev_mode/template.hbs, examples/render_file.rs, examples/script/goals.rhai, src/context.rs, src/error.rs, src/helpers/block_util.rs, src/helpers/helper_each.rs, src/helpers/helper_with.rs, src/lib.rs, src/registry.rs, src/render.rs, src/sources.rs, src/template.rs
This patch adds a new concept in handlebars called dev mode. In dev mode, we will enable some development friendly features.
The first dev mode feature is template auto-reload. In dev-mode, templates that registered from files or directory, are not cached . Changes made in template file will be reflected immediately without restart your server.
In addition to dev mode, I made template mapping a default feature since it's useful to debug any template error in any scenario.
=> Dev mode and template sources

src/partial.rs, src/render.rs
This patch is an attempt to fix #400
=> Nested @partial-block support

src/error.rs
These error messages ended up with a period + colon. For example:
```
Error on accessing array/vector with string index.: invalid digit found in string
```
```
Error with parsing template.: Template error: invalid handlebars syntax.
```
=> Fix punctuation in errors built with `RenderError::from_error`.

src/registry.rs
Allows '/' as trail separator on Windows.
=> (fix) path trail slash check on Windows

examples/decorator/template.hbs, examples/error/template.hbs, examples/partials/base0.hbs, examples/partials/base1.hbs, examples/partials/template2.hbs, examples/render/template.hbs, examples/script/template.hbs, src/grammar.pest, src/grammar.rs, src/helpers/helper_if.rs, src/template.rs
This patch is an attempt to fix #258 with pest grammar. 
The draw back of current solution is it removed whitespaces after `}}` even if there is no line separator. Therefore this is going to be a break change. Case like
```handlebars
{{#each a}}{{this}}{{/each}} {{b}}
```
```json
{"a": [1,2,3,4], "b": "good"}
```
Now renders as `1234good` instead of `1234 good`.
I'm trying to figure out if there is any solution to retain these whitespaces.
Update: the issue is fixed via 181565f
=> Remove line separator for invisible elements

src/lib.rs
This seems to be by far the most popular argument when calling
register_escape_fn(), judging from GitHub code search, and so it seems
worthwhile to mention it here to avoid the need for the people to write
their own trivial escape function doing nothing only to discover that
such function already exists in Handlebars itself.
---
A really trivial PR just to save some time to the others who might also waste time as I did before discovering `no_escape()`.
=> (doc) mention no_escape() in the "Escaping" section

src/context.rs, src/partial.rs
=> Fix issue when upper block has block value

src/grammar.pest, src/grammar.rs, src/lib.rs, tests/escape.rs
=> Fix json string escape

src/error.rs, src/render.rs, src/template.rs
Adopt new clippy rules on uppercase symbol name
=> (fix) fix upper-case acronyms where it is possible

src/json/path.rs, tests/subexpression.rs
Fixes a bug I found when running the fuzzer for a bit after #427 was fixed
Not sure if the test here is in the right place or if you want me to put it in with the other test function.
Ran the fuzzer for a while after this and didn't see any issues. I'll make a new PR for the fuzzing target (or just lump it in here) if you want, it uses [`cargo-fuzz`](https://github.com/rust-fuzz/cargo-fuzz).
=> Fix out of bounds index when parsing JSON path

fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/render_template_no_data.rs
I get *really slow* test cases with this, so I'm guessing there's some non-linear time parsing that can cause extreme slowdowns with this.
You can specify a max length when running the fuzzer, I've found a length of 64 doesn't run into those issues and lets me test for panics, but it might be worth having a look at the slow cases, I've not been able to get a clean test case for the slowdown issue.
=> Add fuzzing harness

src/partial.rs, src/registry.rs
=> Load partial from source when accessing partial in dev mode

CHANGELOG.md, src/error.rs, src/helpers/helper_lookup.rs, src/helpers/mod.rs, src/helpers/scripting.rs, src/macros.rs, src/registry.rs, src/render.rs, tests/subexpression.rs
This patch changes default implementation of `call_inner` from `HelperDef`, and remove unneeded `Option` from return type.
It tries to fix twice-call issue reported in #435 because developer may return `Ok(None)` when they actually want to return Json Null. Previously `Ok(None)` is a special value to indicate the `call_inner` function is not implemented. This patch changed this and avoid misleading.
=> Refactor call_inner default implementation

.github/workflows/main.yml, CHANGELOG.md, Cargo.toml, README.md, examples/partials/template2.hbs, fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/render_template_no_data.rs, src/context.rs, src/error.rs, src/grammar.pest, src/grammar.rs, src/helpers/helper_extras.rs, src/helpers/helper_lookup.rs, src/helpers/mod.rs, src/helpers/scripting.rs, src/json/path.rs, src/lib.rs, src/macros.rs, src/partial.rs, src/registry.rs, src/render.rs, src/template.rs, tests/escape.rs, tests/subexpression.rs
Note that the base branch for this PR is `feature/publish-source-api` (see #415).
=> Merge master and add a test for `register_template_source`

src/helpers/helper_each.rs
I added this test because updating from `3` to `4` broke my software in a weird way, where a variable was noted as not there, but it was there.
So here's a test to check whether things still work with empty iterables in the `#each` helper, because I was not able to get my local clone to run through `cargo test` (some weird issue with pprof not compiling... I don't know. The quick fix is to push this through github actions).
=> Fix: Calling each on empty iterator without else block

examples/render_file/template.hbs, src/grammar.pest, src/grammar.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/template.rs
=> Empty line stripping fix

src/macros.rs, tests/subexpression.rs
Unbound parameters of test expressions now cause an error if strict mode is enabled. For context see issue #449.
=> Error if boolean helper params are missing.

src/grammar.rs, src/helpers/helper_if.rs, src/partial.rs, src/template.rs
This patch adds some corner cases for #448 
- statement with leading white-spaces at the beginning of the template
- partial expression (`{{> foo}}`) should follow the same pattern
=> Helper tag with leading whitespaces fix

CHANGELOG.md, Cargo.toml, src/macros.rs, tests/helper_macro.rs
This PR allows generic types in the simple parameter list of `handlebars_helper!`. For example, the following is now supported:
```rust
handlebars_helper!(date: |dt: DateTime<FixedOffset>| dt.format("%F").to_string());
```
This PR does not allow generic parameters in the hashmap syntax.
Fixes #460
=> Support generic parameters in handlebars_helper macro

src/lib.rs
The old django 1.9 doc is no longer available.  
https://docs.djangoproject.com/en/1.9/ref/templates/language/#template-inheritance
=> fix link to django doc for template inheritance

src/template.rs, tests/escape.rs
For case #467 
This is a regression issue introduced into 4.1.x
=> Whitespaces behind expression are ignored

src/grammar.pest, src/render.rs
=> Fix handling of identifiers which start with numbers

Cargo.toml, src/lib.rs, src/registry.rs, tests/embed.rs, tests/templates/hello.hbs
=> Rust embedded support

src/partial.rs, src/render.rs
Fixes #487
We can only increase `patial_block_depth` for scenarios where
consecutive `@partial-block` are rendered.
=> Fix partial block referencing in nested partials

src/context.rs, src/partial.rs, src/render.rs
Fixes #495 
This patch fixes issue mentioned in #495, that block params like `{{#each data as |name|}}` leaked into partials, so that partial context was override. An example of javascript version is [here](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B~%23*inline%20%5C%22displayName%5C%22~%7D%7D%5CnTemplate%3A%7B%7Bname%7D%7D%5Cn%7B%7B%2Finline%7D%7D%5Cn%7B%7B%23each%20data%20as%20%7Cname%7C%7D%7D%5CnName%3A%7B%7Bname%7D%7D%5Cn%7B%7B%3EdisplayName%20name%3D%5C%22aaa%5C%22%7D%7D%5Cn%7B%7B%2Feach%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%5C%22data%5C%22%3A%20%5B%5C%22hudel%5C%22%2C%20%5C%22test%5C%22%5D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%22%2C%22output%22%3A%22Name%3Ahudel%5CnTemplate …
=> Fix block param scope leaked into partials

src/registry.rs
This pull request was originally for allowing extensions to not be prefixed by a dot which lead to a general refactor of dir_source.
The main change is that tpl_extension in register_templates_directory doesn't need a dot in the front and non-utf8 file names will not be registered unlike before where mangled strings will be registered.
=> Refactor dir_source to be more ideomatic

src/grammar.rs, src/partial.rs, src/render.rs, src/support.rs, src/template.rs
Fixes #504 
This patch implements indent feature for partial statement `{{> partial}}`. Since handlebars 2.0, all text lines generated from `{{> partial}}` follows the indent for that statement.
=> Partial indent support

CHANGELOG.md, src/partial.rs, src/template.rs
[In handlebars.js, `{{~> partial}}` disables indentation for every line of partial content](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23*inline%20%5C%22thepartial%5C%22%7D%7D%5Cn%20%20inner%20first%20line%5Cn%20%20inner%20second%20line%5Cn%7B%7B%2Finline%7D%7D%5Cn%20%20%7B%7B~%3E%20thepartial%7D%7D%5Cnouter%20third%20line%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20firstname%3A%20%5C%22Yehuda%5C%22%2C%5Cn%20%20lastname%3A%20%5C%22Katz%5C%22%2C%5Cn%7D%5Cn%22%2C%22output%22%3A%22%20%20inner%20first%20line%5Cn%20%20inner%20second%20line%5Cnouter%20third%20line%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%2 …
=> Disable partial indent with leading `~`

examples/decorator.rs, examples/render.rs, examples/render_file.rs, src/decorators/mod.rs, src/helpers/mod.rs, src/output.rs, src/render.rs
Upside: It may help (or not) to avoid allocation, rustc, is not able every time able to discard format allocations.
Downsite API change, may not be worth it.
Edit: 
- had some personal mixed results on `cargo bench` so I removed the comments because it was mostly noise to retain the real addition of this PR: adding `write_fmt` to `Output` trait or not, totally ok if it's closed as "not worth the maintaining effort" or "not in the scope of the project" :)
Have a great day
=> feat: Add in trait Output in write_fmt to get access to write! macro

src/block.rs, src/context.rs, src/decorators/inline.rs, src/decorators/mod.rs, src/helpers/block_util.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_raw.rs, src/helpers/helper_with.rs, src/helpers/mod.rs, src/helpers/scripting.rs, src/json/value.rs, src/macros.rs, src/partial.rs, src/registry.rs, src/render.rs, tests/data_helper.rs, tests/embed.rs, tests/helper_function_lifetime.rs, tests/helper_with_space.rs, tests/subexpression.rs
Only type annotations needed to be fixed, all the code actually already supported rendering shorter-lived templates.  
This fixes #529 
This is a breaking change, but it makes this API useful in more contexts, and even simplifies it a bit with fewer lifetime annotations, so I think it's worth it.
@sunng87
=> issue 529: simplify lifetime requirements

src/block.rs, src/lib.rs, src/local_vars.rs
This makes LocalVars public and gives mutable access to it from BlockContext. I need this for [SQLPage](https://github.com/lovasoa/SQLpage)
=> Allow public access to local variables

src/partial.rs
Fixes #534 
In previous implementation, block are pushed to render context at last. However, during the context merge phase, we use `Path::current()` which assumes block already pushed to render context. This patch reorganized its sequence to make sure context is merged with given path.
=> Fix issue when using partial context within each block

src/error.rs, src/lib.rs, src/registry.rs
This allows developers to get the missing variable path from the error and produce a customized hint message to the frontend users.
=> Able to get the missing variable path from error 

src/registry.rs
Fixes #549 
This patch uses `strip_surfix` and `ends_with` to deal with template file names, in order to be compatible with our previous implementation.
=> fix: loading templates which has multiple extensions

src/macros.rs
It is often customary to define a crate wide `Error` and `Result` type. Something like:
```
type Error = ...
type Result<T> = std::result::Result<T, Error>
```
If such `Result<T>` type is in scope when calling the `handlebar_helper!()` macro, compilation fails as the number of template argument does not match.
This commit modified macro to rely explicitely on `std::result::Result<>` instead of the whatever Result type is in scope when the macro is invoked.
=> fix: use std::result::Result instead of Result in handlebar_helper!() macro

examples/decorator.rs, examples/error.rs, examples/render.rs, examples/render_file.rs, src/decorators/inline.rs, src/error.rs, src/helpers/helper_each.rs, src/helpers/helper_if.rs, src/helpers/helper_log.rs, src/helpers/helper_lookup.rs, src/helpers/helper_with.rs, src/json/path.rs, src/lib.rs, src/macros.rs, src/partial.rs, src/registry.rs, src/render.rs, tests/helper_function_lifetime.rs, tests/subexpression.rs
=> Refactor more RenderError into RenderErrorReason

src/helpers/helper_each.rs, src/json/value.rs
Arrays are being rendered with trailing commas
Related to #587 
Verify when rendering an array that last element being rendered does not include a comma and space
=> Render arrays without trailing commas

src/lib.rs
Currently, TemplateErrorReason is not being exported, while RenderErrorReason is.
This PR fixes this inconsistency by exporting TemplateErrorReason.
=> Added TemplateErrorReason to exported types

src/registry.rs, src/sources.rs, tests/embed.rs
Hi! 
Thanks for the library! 
I have a problem while working with RustEmbed struct. I want a live reload, but now it is implemented only for file register, so i used workaround by iterating struct and register using filenames from it, but i  would like to have it implemented by [handlebars-rust](https://github.com/sunng87/handlebars-rust)
This PR adds dev mode for RustEmbed,  [_which if built not in release mode, reads from the file system on each call_](https://github.com/pyrossh/rust-embed#getfile_path-str---optionrust_embedembeddedfile).
Also added method which names templates and filters files like register_templates_directory does.
=> Added dev mode and extension filter for RustEmbed

src/registry.rs
Would you be willing to accept this adjustment to allow for an additional `hidden` parameter to be passed into `register_templates_directory` to control whether hidden files are ignored?
This would allow for template directories that contained hidden files which should be registered.
=> Add hidden flag to control when hidden files are ignored

src/lib.rs
Or is there a specific reason why this is not done?
=> Re-export JsonTruthy

Cargo.toml, src/helpers/mod.rs, src/helpers/string_helpers/mod.rs, src/lib.rs, src/registry.rs
Helpers for converting a text string to `camelCase`, `kebab-case`, `snake_case` etc. Supports case conversions from the `heck` crate. This is an opt-in feature which can be enabled using `string_helpers` feature.
=> Support for case conversion helpers.

src/grammar.pest, src/grammar.rs, src/helpers/helper_if.rs, src/render.rs, src/template.rs
=> Add chained else expression support

src/lib.rs
Looks like you forgot to update the documentation comment when adding the new escape characters.
=> Update lib.rs documentation for escape characters

src/error.rs, src/grammar.pest, src/grammar.rs, src/template.rs
I had an user report being unable to debug a template syntax error, because the error message just said "invalid handlebars syntax" without more details: https://github.com/lovasoa/SQLpage/discussions/275#discussion-6413288
This changes syntax error messages to include the precise source of the syntax error
this also renames some grammar rules to make them easier to understand
=> improve error messages on parse errors

src/error.rs
This just allows one to get the `RenderErrorReason` out of a `RenderError` **by value**.
The current `reason()` function only gives a reference, and the `reason` member is not `pub` (presumably for good reason).
My usecase for this is that I am using `render_to_write` with known, good data.
So the only possible error is an `std::io::Error` from the underlying writer, so I want to return that.
Unfortunately, `std::io::Error` isn't `Clone` so I can't get it out of the `&RenderErrorReason` that I'm currently getting.
I figured this was simple enough to not require a huge discussion in an issue first, but I'll gladly implement a different solution for this usecase if this conversion function is not acceptable for some reason.
Cheers and thank you for the awesome library.
=> impl From<RenderError> for RenderErrorReason

src/partial.rs, src/render.rs, src/template.rs
Currently, nested partials don't indent correctly.
This is due to two problems:
- The `indent` in `RenderContextInner` is not built up correctly
- After a stanalone partial, the next raw text is trimmed, so it will not be indented (no leading newline),
causing it to be misindented.
This PR addresses both issues, causing a simple nested [example](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23*inline%20%5C%22nested_partial%5C%22%7D%7D%5Cn%3Cdiv%3E%5Cn%5Ctcontent%5Cn%3C%2Fdiv%3E%5Cn%7B%7B%2Finline%7D%7D%5Cn%7B%7B%23*inline%20%5C%22partial%5C%22%7D%7D%5Cn%3Cdiv%3E%5Cn%5Ct%7B%7B%3Enested_partial%7D%7D%5Cn%3C%2Fdiv%3E%5Cn%7B%7B%2Finline%7D%7D%5Cn%3Cdiv%3E%5Cn%5Ct%7B%7B%3E%20partial%20%7D%7D%5Cn%3C%2Fdiv%3E%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22i …
=> Fix nested partial indenting

src/context.rs, tests/block_context.rs
Fixes a simple bug in path lookup.
(input: `{"foo": [42], "bar": [1,2,3]}`)
```
let input = r#"
{{#each bar as |x|}}
{{#each ../foo as |y|}}
{{../../foo.0}}: {{../x}}
{{/each}}
{{/each}}
"#;
```
```
42: 
42: 
42: 
```
```
42: 1
42: 2
42: 3
```
=> Fix Nested path lookup bug

examples/block_helper_macro_let.rs, src/block.rs, src/json/value.rs, src/lib.rs
This just adds a simple method: `set_block_param` to the `BlockContext`.
It also makes the members of the (already public) `PathAndJson` struct public
so you can make effective use of it.
The existing `set_block_params` only allows replacing all block parameters.
Because there also is no `get_block_params`, this makes it impossible for a helper to
edit the block parameters effectively.
My usecase was to be able to write a helper that binds a variable to a name.
That helper is so useful that I added it to the examples aswell.
=> Allow users to set single block params.

src/helpers/mod.rs, src/partial.rs, src/render.rs, src/template.rs, tests/whitespace.rs
This is my second attempt at fixing the more involved indenting issues first brought up in #650 .
It turns out that the `Indent` node is simply not powerful enough to handle all cases :(.
We will unfortunately have to dynamically track whether a partial ended on a newline or not.
This PR does exactly that.
Here are some of the more difficult edge cases that this solves:
```
{{#*inline "empty_partial"}}{{/inline}}
<div>
{{> empty_partial}}
</div>
```
```
<div>
</div>
``` 
---
```
{{#*inline "partial"}}foo{{/inline}}
<div>
{{> partial}}
</div>
```
```
<div>
foo</div>
```
(yes, this is indeed correct according to [handlebars js](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23*inline%20%5C%22partial%5C%22%7D%7Dfoo%7B%7B%2Finline%7D%7D%5Cn%3Cdiv …
=> Fix indent v2

src/json/path.rs, src/lib.rs
I'm doing a bit of code generation from the parsed template, and in order to generate based on:
```rust
Path(
Relative(
( 
[Named("visibility")],
"visibility",
),
),
),
```
I've been using the following workaround, which is far from ideal:
```rust
fn path_to_string(path: &Path) -> String {
let raw_path = format!("{:?}", path);
let regex = regex::Regex::new(r#"(?:"|\\")([^\\"]+)(?:"|\\")"#).unwrap();
if let Some(captures) = regex.captures(&raw_path) {
captures.get(1).unwrap().as_str().to_string()
} else {
raw_path
}
}
```
Making `PathSeg` part of the public API allows for cleaner and more direct usage, eliminating the need for such workarounds.
Thank you for your consideration.
=> feat: add PathSeg to public API

src/render.rs, tests/whitespace.rs
This solves an edge case regarding nested, empty partials.
We currently don't restore our trailing newline flag when exiting a partial / helper.
This assumption fails if the partial doesn't produce any content at all.
This PR solves this.
```
{{~#*inline "empty_partial"}}{{/inline}}
{{~#*inline "indented_partial"}}
{{>empty_partial}}foo
{{/inline}}
{{>indented_partial}}
```
```
foo
```
```
foo
```
=> Fix edge case around nested empty partials

benches/bench.rs, src/render.rs, src/support.rs
The current `with_indent` function allocates a string to render the content into for every single  `indent_aware_write`.
It also operates on a per char basis instead of processing full line slices at a time.
This PR fixes this by implementing an improved version that operates directly on the output stream.
In my testing this gives us about a 5 to 15% performance boost :rocket: ,
although the benchmarks are a bit flaky. I also added another benchmark with some 
more nested partials than in the others, which benefits the most from this change.
```
Running benches/bench.rs (target/release/deps/bench-a2a79c58e18ef2a8)
parse_template          time:   [20.801 µs 20.830 µs 20.858 µs]
change: [-0.0628% +0.2014% +0.4363%] (p = 0.12 > 0.05)
No change in performance detected.
render_template …
```
=> Zero alloc indent write

src/render.rs
Hey, I realized that there's one last thing I think we could consider before v6.0.
Now that we no longer clone the `RenderContext` we could get rid of the slightly hacky `RenderContextInner`
and the whole writing through an `Rc` idiom associated with it.
I know I initially said that I don't expect any more breaking changes, 
but I missed that this narrows the lifetime contract on the public `RenderContext` type.
This shouldn't really affect anybody (`'reg: 'rc` is basically assumed everwhere already), 
but as a matter of technicality might be semver incompatible.
This should now really be the last breaking change in the indent patch series though :).
=> Eliminate `RenderContextInner`

src/lib.rs, src/macros.rs
Removed indents in doc comments examples
=> docs: fix code examples formatting

src/helpers/helper_extras.rs
fixes https://github.com/sunng87/handlebars-rust/issues/672
=> implement floating point and string comparisons

Cargo.toml, src/helpers/helper_extras.rs
Fixes #678 
Included a new dependency num-order to compare numbers of different types.
=> fix: improved number compare between different types

src/helpers/helper_extras.rs
Writing ifs with multiple conditions used to be very painful, and not very performant
One had to write {{#if (and (cond1 (and cond2 cond3)))}}
One can now write {{#if (and cond1 cond2 cond3)}}
=> make "and" and "or" accept any number of parameters

Cargo.toml, src/registry.rs, src/template.rs
Dear sunng,
For issue (#666): If you are okay with this type of builder, please let me add it for the other non-exhaustive structs. If there are any issues, let me know so I can fix them before proceeding to add it to the other structs.
=> fix(#666): Add builder for non-exhaustive structs

src/context.rs, src/partial.rs
Fixes #693 
The previous implementation runs into issue with resolving values from blocks. In this patch, I just simplified the implementation by treat partial context as block context parameters.
=> fix: reimplement partial context as block params

src/partial.rs
This patch add support for literal parameters on partial.
Fixes #643
=> fix: partial context with literal parameters

src/context.rs, src/partial.rs, src/render.rs
Fixes #698 #696 
This patch finally reimplements partial's block context correctly. The key is to remove all previous blocks and use a separated one for partial.
It corrects behavior of partial parameter, hash and merge_json:
- if parameters is provided, either as path or literal, use it as base value; otherwise use `this` as base_value
- if hash is provided, always merge it with base value:
- if base value is associative type: object, array, string, merge them as map
- if base value is non-associative type, return hash
otherwise, use base value directly
When partial is rendered, reset blocks.
Tests added.
=> feat: correct implementation of partial block

src/grammar.pest, src/grammar.rs
Fixes #701 
Add `:` in identifier characters
=> fix: allow colons in identifier

src/registry.rs
=> docs: remove incorrect parameters from docstring

src/lib.rs, src/registry.rs
DirectorySourceOptions is `#[non_exhaustive]` which means it cannot be created directly by users of the crate.
DirectorySourceOptions is `#[derive(Builder)]` but the resulting DirectorySourceOptionsBuilder is not exposed to users of the crate.
Because of this only `DirectorySourceOptions::default()` can be used and options cannot be set.
Exposing DirectorySourceOptionsBuilder allows users of this crate to build DirectorySourceOptions.
=> expose DirectorySourceOptionsBuilder & added doc example

src/helpers/helper_extras.rs, src/registry.rs
This PR makes boolean helpers (`eq`, `and`, etc) can be used with `else`.
```handlebars
{{#eq foo bar}}
OK
{{else}}
KO
{{/eq}}
// this still works
{{eq foo bar}}
```
It can be considered as a shorthand for `{{#if (eq a b)}}SUCCESS{{else}}FAIL{{/if}}`.
I need this to improve inter-operability with [handlerbars.java's ConditionalHelpers](https://github.com/jknack/handlebars.java/blob/b8a94d32b57f07e3d286befa3fb3c9c70e66e982/handlebars/src/main/java/com/github/jknack/handlebars/helper/ConditionalHelpers.java#L69)
=> feat: else support for boolean helpers
